#!/usr/bin/env fish

just build || return 1

set -lx BAT_THEME 'Nord'
set -lx BAT_THEME_DARK 'Nord'
set -lx BAT_THEME_LIGHT '1337'

for ex in $argv
    echo
    bat $ex

    systemd-run \
        --scope \
        -p 'MemoryMax=100M' \
        -p 'MemorySwapMax=0' \
        --user \
        tree-sitter \
        highlight \
        --time \
        $ex \
        | bat \
        --paging never \
        --style 'grid,snip'

    systemd-run \
        --scope \
        -p 'MemoryMax=100M' \
        -p 'MemorySwapMax=0' \
        --user \
        tree-sitter \
        parse \
        --time \
        $ex \
        | bat \
        --paging never \
        --language scm \
        --style snip \
        || echo "ERROR Whoops $status"
end
