/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_line_token1 = 1,
  aux_sym_word_token1 = 2,
  aux_sym_word_token2 = 3,
  sym_uuid = 4,
  sym_alias = 5,
  sym_ref = 6,
  sym_tag = 7,
  sym_fmt = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_BANGEoF_LBRACE = 11,
  anon_sym_RBRACEEoF_BANG = 12,
  aux_sym_contents_token1 = 13,
  aux_sym_contents_token2 = 14,
  sym__doc_start = 15,
  sym_papier = 16,
  sym_text = 17,
  sym_line = 18,
  sym_word = 19,
  sym_sub_document = 20,
  sym_title = 21,
  sym_contents = 22,
  sym_raw_contents = 23,
  aux_sym_papier_repeat1 = 24,
  aux_sym_text_repeat1 = 25,
  aux_sym_line_repeat1 = 26,
  aux_sym_contents_repeat1 = 27,
  aux_sym_raw_contents_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_line_token1] = "line_token1",
  [aux_sym_word_token1] = "word_token1",
  [aux_sym_word_token2] = "word_token2",
  [sym_uuid] = "uuid",
  [sym_alias] = "alias",
  [sym_ref] = "ref",
  [sym_tag] = "tag",
  [sym_fmt] = "fmt",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_BANGEoF_LBRACE] = "!EoF{",
  [anon_sym_RBRACEEoF_BANG] = "}EoF!",
  [aux_sym_contents_token1] = "contents_token1",
  [aux_sym_contents_token2] = "contents_token2",
  [sym__doc_start] = "_doc_start",
  [sym_papier] = "papier",
  [sym_text] = "text",
  [sym_line] = "line",
  [sym_word] = "word",
  [sym_sub_document] = "sub_document",
  [sym_title] = "title",
  [sym_contents] = "contents",
  [sym_raw_contents] = "raw_contents",
  [aux_sym_papier_repeat1] = "papier_repeat1",
  [aux_sym_text_repeat1] = "text_repeat1",
  [aux_sym_line_repeat1] = "line_repeat1",
  [aux_sym_contents_repeat1] = "contents_repeat1",
  [aux_sym_raw_contents_repeat1] = "raw_contents_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_line_token1] = aux_sym_line_token1,
  [aux_sym_word_token1] = aux_sym_word_token1,
  [aux_sym_word_token2] = aux_sym_word_token2,
  [sym_uuid] = sym_uuid,
  [sym_alias] = sym_alias,
  [sym_ref] = sym_ref,
  [sym_tag] = sym_tag,
  [sym_fmt] = sym_fmt,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_BANGEoF_LBRACE] = anon_sym_BANGEoF_LBRACE,
  [anon_sym_RBRACEEoF_BANG] = anon_sym_RBRACEEoF_BANG,
  [aux_sym_contents_token1] = aux_sym_contents_token1,
  [aux_sym_contents_token2] = aux_sym_contents_token2,
  [sym__doc_start] = sym__doc_start,
  [sym_papier] = sym_papier,
  [sym_text] = sym_text,
  [sym_line] = sym_line,
  [sym_word] = sym_word,
  [sym_sub_document] = sym_sub_document,
  [sym_title] = sym_title,
  [sym_contents] = sym_contents,
  [sym_raw_contents] = sym_raw_contents,
  [aux_sym_papier_repeat1] = aux_sym_papier_repeat1,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
  [aux_sym_line_repeat1] = aux_sym_line_repeat1,
  [aux_sym_contents_repeat1] = aux_sym_contents_repeat1,
  [aux_sym_raw_contents_repeat1] = aux_sym_raw_contents_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_uuid] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_fmt] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANGEoF_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACEEoF_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_contents_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_contents_token2] = {
    .visible = false,
    .named = false,
  },
  [sym__doc_start] = {
    .visible = false,
    .named = true,
  },
  [sym_papier] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_sub_document] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_contents] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_contents] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_papier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_contents_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_raw_contents_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_closing_brace = 1,
  field_contents = 2,
  field_line = 3,
  field_opening_brace = 4,
  field_title = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_closing_brace] = "closing_brace",
  [field_contents] = "contents",
  [field_line] = "line",
  [field_opening_brace] = "opening_brace",
  [field_title] = "title",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 3},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 3},
  [7] = {.index = 12, .length = 3},
  [8] = {.index = 15, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_title, 1},
  [1] =
    {field_line, 0},
  [2] =
    {field_closing_brace, 3},
    {field_opening_brace, 1},
  [4] =
    {field_closing_brace, 4},
    {field_contents, 3},
    {field_opening_brace, 1},
  [7] =
    {field_line, 0},
    {field_line, 1},
  [9] =
    {field_closing_brace, 4},
    {field_opening_brace, 2},
    {field_title, 1},
  [12] =
    {field_line, 0},
    {field_line, 1},
    {field_line, 2},
  [15] =
    {field_closing_brace, 5},
    {field_contents, 4},
    {field_opening_brace, 2},
    {field_title, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 8,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 9,
  [22] = 20,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(52);
      if (lookahead == '\t') ADVANCE(115);
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '!') ADVANCE(102);
      if (lookahead == '#') ADVANCE(49);
      if (lookahead == '@') ADVANCE(47);
      if (lookahead == '{') ADVANCE(108);
      if (lookahead == '}') ADVANCE(110);
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == ',' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '?') ADVANCE(101);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '\r') ADVANCE(55);
      if (lookahead == ' ') SKIP(1);
      if (lookahead == '!') ADVANCE(56);
      if (lookahead == '#') ADVANCE(98);
      if (lookahead == '@') ADVANCE(96);
      if (lookahead == '{') ADVANCE(109);
      if (lookahead == ',' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '?') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '}') ADVANCE(117);
      if (lookahead == '\r' ||
          lookahead == ' ') ADVANCE(120);
      if (lookahead != 0) ADVANCE(122);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(113);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(34);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(46);
      END_STATE();
    case 8:
      if (lookahead == 'E') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'F') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'F') ADVANCE(3);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == '{') ADVANCE(111);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(8);
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(14);
      END_STATE();
    case 15:
      if (lookahead == '\r' ||
          lookahead == ' ') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(122);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(103);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(7);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(4);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(5);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 40:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 43:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    case 44:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(43);
      END_STATE();
    case 45:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(44);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(45);
      END_STATE();
    case 47:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 48:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(106);
      END_STATE();
    case 50:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(105);
      END_STATE();
    case 51:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '\r') ADVANCE(54);
      if (lookahead == ' ') SKIP(51);
      if (lookahead == '!') ADVANCE(57);
      if (lookahead == '#') ADVANCE(98);
      if (lookahead == '@') ADVANCE(96);
      if (lookahead == ',' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '?') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_line_token1);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_word_token1);
      ADVANCE_MAP(
        '\r', 54,
        '!', 57,
        '#', 98,
        '@', 96,
        ',', 100,
        '.', 100,
        ':', 100,
        ';', 100,
        '?', 100,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(100);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_word_token1);
      ADVANCE_MAP(
        '\r', 55,
        '!', 56,
        '#', 98,
        '@', 96,
        '{', 109,
        ',', 100,
        '.', 100,
        ':', 100,
        ';', 100,
        '?', 100,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(100);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '!') ADVANCE(97);
      if (lookahead == '?') ADVANCE(99);
      if (lookahead == 'E') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(100);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '!') ADVANCE(97);
      if (lookahead == '?') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(100);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '-') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '-') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '-') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '-') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == 'F') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == 'o') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '{') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(105);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_word_token2);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_word_token2);
      if (lookahead == '!') ADVANCE(48);
      if (lookahead == '?') ADVANCE(50);
      if (lookahead == 'E') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_uuid);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_alias);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_ref);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_fmt);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_BANGEoF_LBRACE);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_BANGEoF_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(100);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_RBRACEEoF_BANG);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_RBRACEEoF_BANG);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(122);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_contents_token1);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_contents_token2);
      if (lookahead == '!') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(122);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_contents_token2);
      if (lookahead == 'E') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(122);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_contents_token2);
      if (lookahead == 'F') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(122);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_contents_token2);
      if (lookahead == 'o') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(122);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_contents_token2);
      if (lookahead == '}') ADVANCE(117);
      if (lookahead == '\r' ||
          lookahead == ' ') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(122);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_contents_token2);
      if (lookahead == '\r' ||
          lookahead == ' ') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(122);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_contents_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(122);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 51, .external_lex_state = 1},
  [2] = {.lex_state = 51, .external_lex_state = 1},
  [3] = {.lex_state = 51, .external_lex_state = 1},
  [4] = {.lex_state = 51, .external_lex_state = 1},
  [5] = {.lex_state = 51, .external_lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 51, .external_lex_state = 1},
  [11] = {.lex_state = 51, .external_lex_state = 1},
  [12] = {.lex_state = 51},
  [13] = {.lex_state = 51, .external_lex_state = 1},
  [14] = {.lex_state = 51},
  [15] = {.lex_state = 51, .external_lex_state = 1},
  [16] = {.lex_state = 51, .external_lex_state = 1},
  [17] = {.lex_state = 51, .external_lex_state = 1},
  [18] = {.lex_state = 51, .external_lex_state = 1},
  [19] = {.lex_state = 51, .external_lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 51},
  [22] = {.lex_state = 51},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 15},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 14},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 14},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_line_token1] = ACTIONS(1),
    [aux_sym_word_token2] = ACTIONS(1),
    [sym_uuid] = ACTIONS(1),
    [sym_alias] = ACTIONS(1),
    [sym_ref] = ACTIONS(1),
    [sym_tag] = ACTIONS(1),
    [sym_fmt] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_BANGEoF_LBRACE] = ACTIONS(1),
    [aux_sym_contents_token1] = ACTIONS(1),
    [sym__doc_start] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_papier] = STATE(45),
    [sym_text] = STATE(3),
    [sym_line] = STATE(5),
    [sym_word] = STATE(12),
    [sym_sub_document] = STATE(3),
    [aux_sym_papier_repeat1] = STATE(3),
    [aux_sym_text_repeat1] = STATE(5),
    [aux_sym_line_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_line_token1] = ACTIONS(5),
    [aux_sym_word_token1] = ACTIONS(7),
    [sym_uuid] = ACTIONS(7),
    [sym_alias] = ACTIONS(7),
    [sym_ref] = ACTIONS(7),
    [sym_tag] = ACTIONS(7),
    [sym_fmt] = ACTIONS(7),
    [sym__doc_start] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_text] = STATE(2),
    [sym_line] = STATE(5),
    [sym_word] = STATE(12),
    [sym_sub_document] = STATE(2),
    [aux_sym_papier_repeat1] = STATE(2),
    [aux_sym_text_repeat1] = STATE(5),
    [aux_sym_line_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(11),
    [aux_sym_line_token1] = ACTIONS(13),
    [aux_sym_word_token1] = ACTIONS(16),
    [sym_uuid] = ACTIONS(16),
    [sym_alias] = ACTIONS(16),
    [sym_ref] = ACTIONS(16),
    [sym_tag] = ACTIONS(16),
    [sym_fmt] = ACTIONS(16),
    [sym__doc_start] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_text] = STATE(2),
    [sym_line] = STATE(5),
    [sym_word] = STATE(12),
    [sym_sub_document] = STATE(2),
    [aux_sym_papier_repeat1] = STATE(2),
    [aux_sym_text_repeat1] = STATE(5),
    [aux_sym_line_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(22),
    [aux_sym_line_token1] = ACTIONS(5),
    [aux_sym_word_token1] = ACTIONS(7),
    [sym_uuid] = ACTIONS(7),
    [sym_alias] = ACTIONS(7),
    [sym_ref] = ACTIONS(7),
    [sym_tag] = ACTIONS(7),
    [sym_fmt] = ACTIONS(7),
    [sym__doc_start] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(26), 1,
      aux_sym_line_token1,
    ACTIONS(24), 2,
      sym__doc_start,
      ts_builtin_sym_end,
    STATE(4), 2,
      sym_line,
      aux_sym_text_repeat1,
    STATE(12), 2,
      sym_word,
      aux_sym_line_repeat1,
    ACTIONS(29), 6,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [24] = 5,
    ACTIONS(5), 1,
      aux_sym_line_token1,
    ACTIONS(32), 2,
      sym__doc_start,
      ts_builtin_sym_end,
    STATE(4), 2,
      sym_line,
      aux_sym_text_repeat1,
    STATE(12), 2,
      sym_word,
      aux_sym_line_repeat1,
    ACTIONS(7), 6,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [48] = 6,
    ACTIONS(34), 1,
      aux_sym_line_token1,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      anon_sym_BANGEoF_LBRACE,
    STATE(32), 1,
      sym_title,
    STATE(7), 2,
      sym_word,
      aux_sym_line_repeat1,
    ACTIONS(36), 6,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [73] = 3,
    STATE(8), 2,
      sym_word,
      aux_sym_line_repeat1,
    ACTIONS(42), 3,
      aux_sym_line_token1,
      anon_sym_LBRACE,
      anon_sym_BANGEoF_LBRACE,
    ACTIONS(36), 6,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [91] = 3,
    STATE(8), 2,
      sym_word,
      aux_sym_line_repeat1,
    ACTIONS(44), 3,
      aux_sym_line_token1,
      anon_sym_LBRACE,
      anon_sym_BANGEoF_LBRACE,
    ACTIONS(46), 6,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [109] = 2,
    ACTIONS(51), 1,
      aux_sym_word_token2,
    ACTIONS(49), 9,
      aux_sym_line_token1,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
      anon_sym_LBRACE,
      anon_sym_BANGEoF_LBRACE,
  [124] = 2,
    ACTIONS(53), 2,
      sym__doc_start,
      ts_builtin_sym_end,
    ACTIONS(55), 7,
      aux_sym_line_token1,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [138] = 2,
    ACTIONS(57), 2,
      sym__doc_start,
      ts_builtin_sym_end,
    ACTIONS(59), 7,
      aux_sym_line_token1,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [152] = 3,
    ACTIONS(61), 1,
      aux_sym_line_token1,
    STATE(14), 2,
      sym_word,
      aux_sym_line_repeat1,
    ACTIONS(7), 6,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [168] = 2,
    ACTIONS(63), 2,
      sym__doc_start,
      ts_builtin_sym_end,
    ACTIONS(65), 7,
      aux_sym_line_token1,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [182] = 3,
    ACTIONS(44), 1,
      aux_sym_line_token1,
    STATE(14), 2,
      sym_word,
      aux_sym_line_repeat1,
    ACTIONS(67), 6,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [198] = 2,
    ACTIONS(70), 2,
      sym__doc_start,
      ts_builtin_sym_end,
    ACTIONS(72), 7,
      aux_sym_line_token1,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [212] = 2,
    ACTIONS(74), 2,
      sym__doc_start,
      ts_builtin_sym_end,
    ACTIONS(76), 7,
      aux_sym_line_token1,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [226] = 2,
    ACTIONS(78), 2,
      sym__doc_start,
      ts_builtin_sym_end,
    ACTIONS(80), 7,
      aux_sym_line_token1,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [240] = 2,
    ACTIONS(82), 2,
      sym__doc_start,
      ts_builtin_sym_end,
    ACTIONS(84), 7,
      aux_sym_line_token1,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [254] = 2,
    ACTIONS(86), 2,
      sym__doc_start,
      ts_builtin_sym_end,
    ACTIONS(88), 7,
      aux_sym_line_token1,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [268] = 1,
    ACTIONS(90), 9,
      aux_sym_line_token1,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
      anon_sym_LBRACE,
      anon_sym_BANGEoF_LBRACE,
  [280] = 2,
    ACTIONS(92), 1,
      aux_sym_word_token2,
    ACTIONS(49), 7,
      aux_sym_line_token1,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [293] = 1,
    ACTIONS(90), 7,
      aux_sym_line_token1,
      aux_sym_word_token1,
      sym_uuid,
      sym_alias,
      sym_ref,
      sym_tag,
      sym_fmt,
  [303] = 5,
    ACTIONS(94), 1,
      aux_sym_line_token1,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    ACTIONS(98), 1,
      aux_sym_contents_token1,
    STATE(29), 1,
      aux_sym_contents_repeat1,
    STATE(41), 1,
      sym_contents,
  [319] = 5,
    ACTIONS(100), 1,
      aux_sym_line_token1,
    ACTIONS(102), 1,
      anon_sym_RBRACEEoF_BANG,
    ACTIONS(104), 1,
      aux_sym_contents_token2,
    STATE(30), 1,
      aux_sym_raw_contents_repeat1,
    STATE(47), 1,
      sym_raw_contents,
  [335] = 5,
    ACTIONS(100), 1,
      aux_sym_line_token1,
    ACTIONS(104), 1,
      aux_sym_contents_token2,
    ACTIONS(106), 1,
      anon_sym_RBRACEEoF_BANG,
    STATE(30), 1,
      aux_sym_raw_contents_repeat1,
    STATE(43), 1,
      sym_raw_contents,
  [351] = 5,
    ACTIONS(94), 1,
      aux_sym_line_token1,
    ACTIONS(98), 1,
      aux_sym_contents_token1,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      aux_sym_contents_repeat1,
    STATE(42), 1,
      sym_contents,
  [367] = 4,
    ACTIONS(110), 1,
      aux_sym_line_token1,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    ACTIONS(115), 1,
      aux_sym_contents_token1,
    STATE(27), 1,
      aux_sym_contents_repeat1,
  [380] = 4,
    ACTIONS(118), 1,
      aux_sym_line_token1,
    ACTIONS(121), 1,
      anon_sym_RBRACEEoF_BANG,
    ACTIONS(123), 1,
      aux_sym_contents_token2,
    STATE(28), 1,
      aux_sym_raw_contents_repeat1,
  [393] = 4,
    ACTIONS(94), 1,
      aux_sym_line_token1,
    ACTIONS(98), 1,
      aux_sym_contents_token1,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      aux_sym_contents_repeat1,
  [406] = 4,
    ACTIONS(100), 1,
      aux_sym_line_token1,
    ACTIONS(104), 1,
      aux_sym_contents_token2,
    ACTIONS(128), 1,
      anon_sym_RBRACEEoF_BANG,
    STATE(28), 1,
      aux_sym_raw_contents_repeat1,
  [419] = 1,
    ACTIONS(130), 3,
      aux_sym_line_token1,
      anon_sym_RBRACE,
      aux_sym_contents_token1,
  [425] = 3,
    ACTIONS(132), 1,
      aux_sym_line_token1,
    ACTIONS(134), 1,
      anon_sym_LBRACE,
    ACTIONS(136), 1,
      anon_sym_BANGEoF_LBRACE,
  [435] = 1,
    ACTIONS(138), 3,
      aux_sym_line_token1,
      anon_sym_RBRACEEoF_BANG,
      aux_sym_contents_token2,
  [441] = 1,
    ACTIONS(140), 3,
      aux_sym_line_token1,
      anon_sym_RBRACE,
      aux_sym_contents_token1,
  [447] = 1,
    ACTIONS(142), 3,
      aux_sym_line_token1,
      anon_sym_RBRACEEoF_BANG,
      aux_sym_contents_token2,
  [453] = 1,
    ACTIONS(144), 1,
      aux_sym_line_token1,
  [457] = 1,
    ACTIONS(146), 1,
      aux_sym_line_token1,
  [461] = 1,
    ACTIONS(148), 1,
      aux_sym_line_token1,
  [465] = 1,
    ACTIONS(150), 1,
      aux_sym_line_token1,
  [469] = 1,
    ACTIONS(152), 1,
      aux_sym_contents_token2,
  [473] = 1,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
  [477] = 1,
    ACTIONS(156), 1,
      anon_sym_RBRACE,
  [481] = 1,
    ACTIONS(156), 1,
      anon_sym_RBRACEEoF_BANG,
  [485] = 1,
    ACTIONS(158), 1,
      aux_sym_line_token1,
  [489] = 1,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
  [493] = 1,
    ACTIONS(162), 1,
      aux_sym_line_token1,
  [497] = 1,
    ACTIONS(154), 1,
      anon_sym_RBRACEEoF_BANG,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 24,
  [SMALL_STATE(6)] = 48,
  [SMALL_STATE(7)] = 73,
  [SMALL_STATE(8)] = 91,
  [SMALL_STATE(9)] = 109,
  [SMALL_STATE(10)] = 124,
  [SMALL_STATE(11)] = 138,
  [SMALL_STATE(12)] = 152,
  [SMALL_STATE(13)] = 168,
  [SMALL_STATE(14)] = 182,
  [SMALL_STATE(15)] = 198,
  [SMALL_STATE(16)] = 212,
  [SMALL_STATE(17)] = 226,
  [SMALL_STATE(18)] = 240,
  [SMALL_STATE(19)] = 254,
  [SMALL_STATE(20)] = 268,
  [SMALL_STATE(21)] = 280,
  [SMALL_STATE(22)] = 293,
  [SMALL_STATE(23)] = 303,
  [SMALL_STATE(24)] = 319,
  [SMALL_STATE(25)] = 335,
  [SMALL_STATE(26)] = 351,
  [SMALL_STATE(27)] = 367,
  [SMALL_STATE(28)] = 380,
  [SMALL_STATE(29)] = 393,
  [SMALL_STATE(30)] = 406,
  [SMALL_STATE(31)] = 419,
  [SMALL_STATE(32)] = 425,
  [SMALL_STATE(33)] = 435,
  [SMALL_STATE(34)] = 441,
  [SMALL_STATE(35)] = 447,
  [SMALL_STATE(36)] = 453,
  [SMALL_STATE(37)] = 457,
  [SMALL_STATE(38)] = 461,
  [SMALL_STATE(39)] = 465,
  [SMALL_STATE(40)] = 469,
  [SMALL_STATE(41)] = 473,
  [SMALL_STATE(42)] = 477,
  [SMALL_STATE(43)] = 481,
  [SMALL_STATE(44)] = 485,
  [SMALL_STATE(45)] = 489,
  [SMALL_STATE(46)] = 493,
  [SMALL_STATE(47)] = 497,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_papier, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_papier_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_papier_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [16] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_papier_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_papier_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_papier, 1, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_document, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_document, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_document, 6, 0, 8),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_document, 6, 0, 8),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_document, 3, 0, 1),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_document, 3, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_document, 4, 0, 3),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_document, 4, 0, 3),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_document, 5, 0, 4),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_document, 5, 0, 4),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_document, 5, 0, 6),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_document, 5, 0, 6),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_contents_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_contents_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_contents_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_raw_contents_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_raw_contents_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_raw_contents_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contents, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_contents, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_contents_repeat1, 1, 0, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_raw_contents_repeat1, 2, 0, 5),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_contents_repeat1, 3, 0, 7),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_raw_contents_repeat1, 1, 0, 2),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [160] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__doc_start = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__doc_start] = sym__doc_start,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__doc_start] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_papier_external_scanner_create(void);
void tree_sitter_papier_external_scanner_destroy(void *);
bool tree_sitter_papier_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_papier_external_scanner_serialize(void *, char *);
void tree_sitter_papier_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_papier(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_papier_external_scanner_create,
      tree_sitter_papier_external_scanner_destroy,
      tree_sitter_papier_external_scanner_scan,
      tree_sitter_papier_external_scanner_serialize,
      tree_sitter_papier_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "papier",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
